import Head from 'next/head'
import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import Post from '../components/Post'
import SearchBar from '../components/SearchBar'
import Header from '../components/Header'
import {sortByDate} from '../utils'

export default function Home({ posts }) {
  //console.log(posts);
  return (
    <div>
      <Head>
        <title>Alex Cucos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <Header />
      <SearchBar />

      {/* <a href="publish/Publish" className="btn publish">Publish</a> */}
      <div className="posts">
        {posts.map((post, index) => (
          <Post key={index} post={post} />
        ))}
      </div>
    </div>

  )
}


export async function getStaticProps(){
  //get files from post dir
  const files = fs.readdirSync(path.join('posts'))
  

  //get slug & front-matter from posts
  const posts = files.map(filename=> {
    const slug = filename.replace('.md', '')
    
    const markdownWithMeta = fs.readFileSync(path.join('posts', filename), 'utf-8') 

    const { data:frontMatter } = matter(markdownWithMeta)
    
    return {
      slug,
      frontMatter,
    }
  })
  return {
    props: {
      posts: posts.sort(sortByDate)
    }
  }
}


